# Generated by Django 5.2.13 on 2026-05-20

import secrets
import string

from django.conf import settings
from django.db import migrations

_ALPHABET = string.ascii_uppercase + string.digits
_PREFIX = "RWG"


def _new_code() -> str:
    return f"{_PREFIX}{''.join(secrets.choice(_ALPHABET) for _ in range(8))}"


def _unique_code(ReferralCode) -> str:
    for _ in range(80):
        code = _new_code()
        if not ReferralCode.objects.filter(code=code).exists():
            return code
    raise RuntimeError("Could not generate unique referral code while backfilling.")


def forwards(apps, schema_editor):
    User = apps.get_model(*settings.AUTH_USER_MODEL.split("."))
    Wallet = apps.get_model("wallet", "Wallet")
    ReferralCode = apps.get_model("referral", "ReferralCode")

    for user in User.objects.all().iterator():
        Wallet.objects.get_or_create(user=user)
        ReferralCode.objects.get_or_create(
            user=user,
            defaults={"code": _unique_code(ReferralCode)},
        )


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0001_initial"),
        ("referral", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]

