# Generated by Django 5.2.13 on 2026-05-20 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0002_backfill_wallet_and_referral'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralRewardConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='default', editable=False, max_length=32, unique=True)),
                ('referral_amount_credits', models.PositiveBigIntegerField(default=0, help_text='Credits rewarded to the owner of a valid referral code on successful signup.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Referral Reward Config',
                'verbose_name_plural': 'Referral Reward Config',
            },
        ),
    ]
