# Generated by Django 5.2.13 on 2026-05-20

from django.db import migrations


def forwards(apps, schema_editor):
    ReferralRewardConfig = apps.get_model("referral", "ReferralRewardConfig")
    ReferralRewardConfig.objects.get_or_create(
        key="default",
        defaults={"referral_amount_credits": 0},
    )


class Migration(migrations.Migration):
    dependencies = [
        ("referral", "0003_referralrewardconfig"),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]

