# Generated by Django 5.2.13 on 2026-05-21 02:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0004_seed_referralrewardconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_credits', models.PositiveBigIntegerField(default=0)),
                ('channel', models.CharField(choices=[('signup', 'Signup'), ('manual', 'Manual')], max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referral_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='referral.referralcode')),
                ('referred_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_redemption', to=settings.AUTH_USER_MODEL)),
                ('referrer_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['referrer_user', '-created_at'], name='referral_re_referre_faee37_idx'), models.Index(fields=['channel'], name='referral_re_channel_efa659_idx')],
            },
        ),
    ]
