# Generated by Django 5.2.13 on 2026-05-23 02:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('ev_scooter', 'EV scooter'), ('ev_bike', 'EV bike'), ('bike', 'Bike'), ('scooter', 'Scooter'), ('other', 'Other')], default='ev_scooter', max_length=32)),
                ('company_name', models.CharField(blank=True, default='', max_length=120)),
                ('model_name', models.CharField(blank=True, default='', max_length=120)),
                ('registration_number', models.CharField(blank=True, default='', max_length=40)),
                ('chassis_number', models.CharField(blank=True, default='', max_length=80)),
                ('battery_number', models.CharField(blank=True, default='', max_length=80)),
                ('color', models.CharField(blank=True, default='', max_length=60)),
                ('purchase_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
                'indexes': [models.Index(fields=['user'], name='vehicle_veh_user_id_460278_idx'), models.Index(fields=['registration_number'], name='vehicle_veh_registr_5efd21_idx'), models.Index(fields=['chassis_number'], name='vehicle_veh_chassis_d8a697_idx')],
            },
        ),
    ]
