# Generated by Django 5.2.13 on 2026-05-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicle", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="vehicle_type",
            field=models.CharField(
                choices=[
                    ("ev_scooter", "EV scooter"),
                    ("ev_bike", "EV bike"),
                    ("bike", "Petrol"),
                    ("scooter", "Scooter"),
                    ("other", "Other"),
                ],
                default="ev_scooter",
                max_length=32,
            ),
        ),
    ]
