# Generated by Django 5.2.13 on 2026-05-21 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='default', editable=False, max_length=32, unique=True)),
                ('version_name', models.CharField(default='1.0.0', help_text='Latest mandatory app version name/code (example: 1.0.3).', max_length=40)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'App Update Version',
                'verbose_name_plural': 'App Update Version',
            },
        ),
    ]
