# Generated by Django 5.2.13 on 2026-05-21 03:56

from django.db import migrations


def seed_app_version_config(apps, schema_editor):
    AppVersionConfig = apps.get_model("update", "AppVersionConfig")
    AppVersionConfig.objects.get_or_create(
        key="default",
        defaults={"version_name": "1.0.0"},
    )


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_app_version_config, migrations.RunPython.noop),
    ]
