# Generated by Django 5.2.13 on 2026-05-02 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsubmission',
            name='inquiry_kind',
            field=models.CharField(choices=[('general', 'General enquiry'), ('buy_ev', 'Buy EV / finance'), ('rent_ev', 'Rent EV'), ('charging', 'Charging & locations'), ('account', 'Account & login'), ('payout', 'Payout issue'), ('safety', 'Safety help'), ('order', 'Order support'), ('account_block', 'Account block'), ('callback', 'Book callback (EV)'), ('feedback', 'Feedback'), ('bug', 'Bug report'), ('other', 'Other')], db_index=True, max_length=32),
        ),
    ]
