// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdRBwqfSmpU2XwZW-xLPfT1h8-rHy2l-0',
    appId: '1:826124088092:web:ad74e24dcec8f10e0700d9',
    messagingSenderId: '826124088092',
    projectId: 'rider-app-notification-57a4e',
    authDomain: 'rider-app-notification-57a4e.firebaseapp.com',
    storageBucket: 'rider-app-notification-57a4e.firebasestorage.app',
    measurementId: 'G-DNB70YX33Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0hKeIhos_THrtz46D_fLuxC6uE_3Uja8',
    appId: '1:826124088092:android:ed0099492ff91e940700d9',
    messagingSenderId: '826124088092',
    projectId: 'rider-app-notification-57a4e',
    storageBucket: 'rider-app-notification-57a4e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDslubi9j9AF_Owbh-ITGxnODEMMU7Vuc8',
    appId: '1:826124088092:ios:73f987f6fc527f0c0700d9',
    messagingSenderId: '826124088092',
    projectId: 'rider-app-notification-57a4e',
    storageBucket: 'rider-app-notification-57a4e.firebasestorage.app',
    iosBundleId: 'com.ridewithgarv.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDslubi9j9AF_Owbh-ITGxnODEMMU7Vuc8',
    appId: '1:826124088092:ios:73f987f6fc527f0c0700d9',
    messagingSenderId: '826124088092',
    projectId: 'rider-app-notification-57a4e',
    storageBucket: 'rider-app-notification-57a4e.firebasestorage.app',
    iosBundleId: 'com.ridewithgarv.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdRBwqfSmpU2XwZW-xLPfT1h8-rHy2l-0',
    appId: '1:826124088092:web:dcf37b63960f8e5b0700d9',
    messagingSenderId: '826124088092',
    projectId: 'rider-app-notification-57a4e',
    authDomain: 'rider-app-notification-57a4e.firebaseapp.com',
    storageBucket: 'rider-app-notification-57a4e.firebasestorage.app',
    measurementId: 'G-TRNJZJJ08V',
  );
}
