# Generated by Django 5.2.13 on 2026-05-23 02:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicle', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RSATicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, default='', max_length=20)),
                ('alternate_phone_number', models.CharField(blank=True, default='', max_length=20)),
                ('region', models.CharField(max_length=80)),
                ('issue', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True, default='')),
                ('gps_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('gps_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('assigned', 'Assigned'), ('in_progress', 'In progress'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], default='new', max_length=24)),
                ('assigned_to_name', models.CharField(blank=True, default='', max_length=120)),
                ('admin_notes', models.TextField(blank=True, default='')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsa_tickets', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rsa_tickets', to='vehicle.vehicle')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['user', '-created_at'], name='rsa_rsatick_user_id_6130b2_idx'), models.Index(fields=['status', '-created_at'], name='rsa_rsatick_status_6bfe9c_idx'), models.Index(fields=['region'], name='rsa_rsatick_region_2a4129_idx'), models.Index(fields=['issue'], name='rsa_rsatick_issue_554eb4_idx')],
            },
        ),
    ]
