# Generated by Django 5.2.13 on 2026-05-23 02:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RSATicketHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('created', 'Created'), ('status_changed', 'Status changed'), ('note_added', 'Note added'), ('assigned', 'Assigned'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], max_length=32)),
                ('from_status', models.CharField(blank=True, default='', max_length=24)),
                ('to_status', models.CharField(blank=True, default='', max_length=24)),
                ('note', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='rsa.rsaticket')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rsa_history_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['ticket', '-created_at'], name='rsa_rsatick_ticket__f46f4b_idx'), models.Index(fields=['user', '-created_at'], name='rsa_rsatick_user_id_fab1c3_idx'), models.Index(fields=['event'], name='rsa_rsatick_event_3ab4df_idx')],
            },
        ),
    ]
