# Generated by Django 5.2.13 on 2026-05-01 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EvLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(default='kml', max_length=120)),
                ('source_url', models.CharField(max_length=500)),
                ('external_id', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('geometry_type', models.CharField(default='Point', max_length=30)),
                ('raw_coordinates', models.TextField(blank=True)),
                ('raw_extended_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', '-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('source_url', 'external_id'), name='unique_ev_location_per_source')],
            },
        ),
    ]
