# Generated by Django 5.2.13 on 2026-05-02 06:52

import apps.ev.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ev', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyEvPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('company_name', models.CharField(max_length=160)),
                ('tagline', models.CharField(max_length=280)),
                ('ex_showroom_from', models.DecimalField(decimal_places=2, max_digits=12)),
                ('documents_required', models.JSONField(blank=True, default=apps.ev.models._empty_doc_list)),
                ('accent_a_hex', models.CharField(help_text='e.g. #0D9488', max_length=9)),
                ('accent_b_hex', models.CharField(help_text='e.g. #14B8A6', max_length=9)),
                ('image_url', models.URLField(blank=True)),
                ('emi_available', models.BooleanField(default=True)),
                ('down_payment_options_available', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'company_name', 'slug'],
            },
        ),
    ]
