# Generated by Django 5.2.13 on 2026-05-02 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ev', '0003_seed_buy_ev_demo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvPlanInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('buy', 'Buy EV'), ('rent', 'Rent EV')], db_index=True, max_length=8)),
                ('plan_slug', models.SlugField(max_length=80)),
                ('partner_label', models.CharField(blank=True, help_text='Brand / partner name snapshot for admin (from Buy plan or client for rent).', max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ev_plan_interests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'channel', 'plan_slug'), name='unique_ev_plan_interest_user_channel_slug')],
            },
        ),
    ]
