# Generated by Django 5.2.13 on 2026-05-02 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def forwards_fill_buy_plan_fk(apps, schema_editor):
    EvPlanInterest = apps.get_model("ev", "EvPlanInterest")
    BuyEvPlan = apps.get_model("ev", "BuyEvPlan")
    for row in EvPlanInterest.objects.filter(channel="buy"):
        slug = (row.plan_slug or "").strip()
        if not slug:
            continue
        plan = BuyEvPlan.objects.filter(slug=slug).first()
        if plan is None:
            continue
        EvPlanInterest.objects.filter(pk=row.pk).update(buy_plan_id=plan.id, plan_slug=None)


def backwards_noop(apps, schema_editor):
    EvPlanInterest = apps.get_model("ev", "EvPlanInterest")
    BuyEvPlan = apps.get_model("ev", "BuyEvPlan")
    for row in EvPlanInterest.objects.filter(channel="buy", buy_plan_id__isnull=False).iterator():
        plan = BuyEvPlan.objects.filter(pk=row.buy_plan_id).first()
        slug = plan.slug if plan else ""
        EvPlanInterest.objects.filter(pk=row.pk).update(plan_slug=slug, buy_plan_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('ev', '0004_ev_plan_interest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='evplaninterest',
            name='unique_ev_plan_interest_user_channel_slug',
        ),
        migrations.AddField(
            model_name='evplaninterest',
            name='buy_plan',
            field=models.ForeignKey(blank=True, help_text='Set for Buy EV — links to the exact catalog row.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='ev.buyevplan'),
        ),
        migrations.AlterField(
            model_name='evplaninterest',
            name='partner_label',
            field=models.CharField(blank=True, help_text='Snapshot / rent label for admin list.', max_length=160),
        ),
        migrations.AlterField(
            model_name='evplaninterest',
            name='plan_slug',
            field=models.SlugField(blank=True, max_length=80, null=True),
        ),
        migrations.RunPython(forwards_fill_buy_plan_fk, backwards_noop),
        migrations.AddConstraint(
            model_name='evplaninterest',
            constraint=models.UniqueConstraint(condition=models.Q(('buy_plan__isnull', False), ('channel', 'buy')), fields=('user', 'buy_plan'), name='unique_ev_interest_user_buy_plan'),
        ),
        migrations.AddConstraint(
            model_name='evplaninterest',
            constraint=models.UniqueConstraint(condition=models.Q(('channel', 'rent')), fields=('user', 'plan_slug', 'channel'), name='unique_ev_interest_user_rent_slug'),
        ),
    ]
