# Generated by Django 5.2.13 on 2026-05-02 07:12

import apps.ev.models
import django.db.models.deletion
from decimal import Decimal

from django.conf import settings
from django.db import migrations, models


def seed_rent_catalog_and_link_interests(apps, schema_editor):
    RentEvPlan = apps.get_model("ev", "RentEvPlan")
    EvPlanInterest = apps.get_model("ev", "EvPlanInterest")

    catalog = [
        {
            "slug": "hala",
            "company_name": "Hala",
            "tagline": "NCR riders · daily & weekly EV plans",
            "security_deposit": Decimal("4410"),
            "weekly_rent": Decimal("1610"),
            "daily_rent": Decimal("230"),
            "documents_required": ["Aadhar Card", "Pan Card", "Selfie"],
            "accent_a_hex": "#2563EB",
            "accent_b_hex": "#06B6D4",
            "image_url": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=1280&q=85",
            "featured": True,
            "sort_order": 10,
        },
        {
            "slug": "zypp",
            "company_name": "Zypp Electric",
            "tagline": "Fleet scooters · quick rider onboarding",
            "security_deposit": Decimal("3500"),
            "weekly_rent": Decimal("1899"),
            "daily_rent": Decimal("285"),
            "documents_required": ["Aadhar Card", "Driving License", "Selfie"],
            "accent_a_hex": "#047857",
            "accent_b_hex": "#34D399",
            "image_url": "https://images.unsplash.com/photo-1571068316344-75bc76f77890?auto=format&fit=crop&w=1280&q=85",
            "featured": True,
            "sort_order": 20,
        },
        {
            "slug": "metroride",
            "company_name": "MetroRide",
            "tagline": "Delhi–Noida–Gurugram coverage",
            "security_deposit": Decimal("5000"),
            "weekly_rent": Decimal("1750"),
            "daily_rent": Decimal("265"),
            "documents_required": ["Aadhar Card", "Pan Card", "Address proof", "Selfie"],
            "accent_a_hex": "#4F46E5",
            "accent_b_hex": "#818CF8",
            "image_url": "https://images.unsplash.com/photo-1485965120184-e220f721d03e?auto=format&fit=crop&w=1280&q=85",
            "featured": False,
            "sort_order": 30,
        },
        {
            "slug": "boltwheels",
            "company_name": "Bolt Wheels",
            "tagline": "Low deposit options for new riders",
            "security_deposit": Decimal("2999"),
            "weekly_rent": Decimal("1549"),
            "daily_rent": Decimal("240"),
            "documents_required": ["Aadhar Card", "Pan Card", "Selfie"],
            "accent_a_hex": "#EA580C",
            "accent_b_hex": "#F97316",
            "image_url": "https://images.unsplash.com/photo-1568772585407-9361d9cd87d5?auto=format&fit=crop&w=1280&q=85",
            "featured": False,
            "sort_order": 40,
        },
        {
            "slug": "cityscoot",
            "company_name": "CityScoot Delhi",
            "tagline": "Swap batteries · longer shifts",
            "security_deposit": Decimal("4800"),
            "weekly_rent": Decimal("2100"),
            "daily_rent": Decimal("320"),
            "documents_required": ["Aadhar Card", "Pan Card", "Bank statement", "Selfie"],
            "accent_a_hex": "#7C3AED",
            "accent_b_hex": "#A78BFA",
            "image_url": "https://images.unsplash.com/photo-1449426468159-96d0d0526911?auto=format&fit=crop&w=1280&q=85",
            "featured": False,
            "sort_order": 50,
        },
        {
            "slug": "greenlane",
            "company_name": "GreenLane EV",
            "tagline": "Weekly flexible extensions",
            "security_deposit": Decimal("4200"),
            "weekly_rent": Decimal("1680"),
            "daily_rent": Decimal("255"),
            "documents_required": ["Aadhar Card", "Selfie"],
            "accent_a_hex": "#0D9488",
            "accent_b_hex": "#2DD4BF",
            "image_url": "https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=1280&q=85",
            "featured": False,
            "sort_order": 60,
        },
    ]
    common = {"is_active": True}
    for row in catalog:
        slug = row["slug"]
        defaults = {k: v for k, v in row.items() if k != "slug"}
        defaults.update(common)
        RentEvPlan.objects.update_or_create(slug=slug, defaults=defaults)

    for interest in EvPlanInterest.objects.filter(channel="rent"):
        slug = (interest.plan_slug or "").strip()
        if not slug:
            continue
        rp = RentEvPlan.objects.filter(slug=slug).first()
        if rp is None:
            continue
        EvPlanInterest.objects.filter(pk=interest.pk).update(rent_plan_id=rp.id, plan_slug=None)


def backwards_rent_seed(apps, schema_editor):
    EvPlanInterest = apps.get_model("ev", "EvPlanInterest")
    RentEvPlan = apps.get_model("ev", "RentEvPlan")
    for row in EvPlanInterest.objects.filter(channel="rent", rent_plan_id__isnull=False).iterator():
        rp = RentEvPlan.objects.filter(pk=row.rent_plan_id).first()
        slug = rp.slug if rp else ""
        EvPlanInterest.objects.filter(pk=row.pk).update(plan_slug=slug or None, rent_plan_id=None)
    RentEvPlan.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('ev', '0005_ev_interest_buy_plan_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RentEvPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('company_name', models.CharField(max_length=160)),
                ('tagline', models.CharField(max_length=280)),
                ('security_deposit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('weekly_rent', models.DecimalField(decimal_places=2, max_digits=12)),
                ('daily_rent', models.DecimalField(decimal_places=2, max_digits=12)),
                ('documents_required', models.JSONField(blank=True, default=apps.ev.models._empty_doc_list)),
                ('accent_a_hex', models.CharField(help_text='e.g. #2563EB', max_length=9)),
                ('accent_b_hex', models.CharField(max_length=9)),
                ('image_url', models.URLField(blank=True)),
                ('featured', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'company_name', 'slug'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='evplaninterest',
            name='unique_ev_interest_user_rent_slug',
        ),
        migrations.AlterField(
            model_name='evplaninterest',
            name='buy_plan',
            field=models.ForeignKey(blank=True, help_text='Buy EV catalog row.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='ev.buyevplan'),
        ),
        migrations.AlterField(
            model_name='evplaninterest',
            name='partner_label',
            field=models.CharField(blank=True, help_text='Snapshot for admin list.', max_length=160),
        ),
        migrations.AddField(
            model_name='evplaninterest',
            name='rent_plan',
            field=models.ForeignKey(blank=True, help_text='Rent EV catalog row.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='ev.rentevplan'),
        ),
        migrations.RunPython(seed_rent_catalog_and_link_interests, backwards_rent_seed),
        migrations.AddConstraint(
            model_name='evplaninterest',
            constraint=models.UniqueConstraint(condition=models.Q(('channel', 'rent'), ('rent_plan__isnull', False)), fields=('user', 'rent_plan'), name='unique_ev_interest_user_rent_plan'),
        ),
    ]
