# Generated by Django 5.2.13 on 2026-05-01 02:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Required at signup.', max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 10-15 digits (optional leading +).', regex='^\\+?[0-9]{10,15}$')])),
                ('profile_photo', models.ImageField(blank=True, help_text='Required by frontend signup flow; enforced at API/serializer layer.', null=True, upload_to='rider_profiles/')),
                ('rider_id', models.CharField(blank=True, max_length=64)),
                ('rider_company', models.CharField(blank=True, max_length=80)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('preferred_language', models.CharField(default='en', max_length=20)),
                ('is_phone_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rider_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
