# Generated by Django 5.2.13 on 2026-05-02 03:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(help_text='Post text content.')),
                ('image', models.ImageField(blank=True, help_text='At most one image per post (enforce in API).', null=True, upload_to='post_images/%Y/%m/')),
                ('city', models.CharField(db_index=True, help_text='Mandatory launch metadata (NCR city etc.).', max_length=80)),
                ('company', models.CharField(db_index=True, help_text="Delivery company; use predefined label or 'Other'.", max_length=120)),
                ('is_anonymous', models.BooleanField(default=False, help_text='If true, hide author from riders in feed; admins still see author.')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft-delete: hidden from riders, retained for admin.')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'city'], name='posts_post_created_ddbe5b_idx'), models.Index(fields=['is_deleted', '-created_at'], name='posts_post_is_dele_af1c37_idx')],
            },
        ),
    ]
