# Generated by Django 5.2.13 on 2026-05-02 03:46

from django.db import migrations, models


def seed_post_meta(apps, schema_editor):
    PostCityOption = apps.get_model("posts", "PostCityOption")
    PostCompanyOption = apps.get_model("posts", "PostCompanyOption")
    PostIssueTypeOption = apps.get_model("posts", "PostIssueTypeOption")

    for order, label in enumerate(["Delhi", "Noida", "Gurgaon"]):
        PostCityOption.objects.get_or_create(
            label=label,
            defaults={"sort_order": order, "is_active": True},
        )

    for order, label in enumerate(["Blinkit", "Zepto", "Swiggy", "Other"]):
        PostCompanyOption.objects.get_or_create(
            label=label,
            defaults={"sort_order": order, "is_active": True},
        )

    for order, label in enumerate(["Payment", "Safety", "Account", "Route"]):
        PostIssueTypeOption.objects.get_or_create(
            label=label,
            defaults={"sort_order": order, "is_active": True},
        )


def unseed_post_meta(apps, schema_editor):
    PostCityOption = apps.get_model("posts", "PostCityOption")
    PostCompanyOption = apps.get_model("posts", "PostCompanyOption")
    PostIssueTypeOption = apps.get_model("posts", "PostIssueTypeOption")
    PostCityOption.objects.all().delete()
    PostCompanyOption.objects.all().delete()
    PostIssueTypeOption.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCityOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80, unique=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'post city option',
                'verbose_name_plural': 'post city options',
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='PostCompanyOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120, unique=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'post company option',
                'verbose_name_plural': 'post company options',
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='PostIssueTypeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80, unique=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'post issue type option',
                'verbose_name_plural': 'post issue type options',
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.RunPython(seed_post_meta, unseed_post_meta),
    ]
