# Generated by Django 5.2.13 on 2026-05-26 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('icon_name', models.CharField(blank=True, help_text='Flutter icon name or identifier (e.g. restaurant_menu_rounded)', max_length=80)),
                ('accent_color', models.CharField(default='#FC8019', help_text='Hex color code (e.g. #FC8019)', max_length=10)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'onboarding category',
                'verbose_name_plural': 'onboarding categories',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120, unique=True)),
                ('logo_url', models.URLField(blank=True, help_text='Optional web URL for company logo/icon', null=True)),
                ('brand_color', models.CharField(default='#000000', help_text='Hex color code (e.g. #E23744)', max_length=10)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='posts.onboardingcategory')),
            ],
            options={
                'verbose_name': 'onboarding company',
                'verbose_name_plural': 'onboarding companies',
                'ordering': ['sort_order', 'label'],
            },
        ),
    ]
