# Generated by Django 5.2.13 on 2026-05-26 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_onboardingcategory_onboardingcompany'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onboardingcompany',
            name='category',
        ),
        migrations.AddField(
            model_name='postcompanyoption',
            name='brand_color',
            field=models.CharField(blank=True, default='#0B1F3A', max_length=20),
        ),
        migrations.AddField(
            model_name='postcompanyoption',
            name='category',
            field=models.CharField(default='Food Delivery', max_length=80),
        ),
        migrations.AddField(
            model_name='postcompanyoption',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
        migrations.DeleteModel(
            name='OnboardingCategory',
        ),
        migrations.DeleteModel(
            name='OnboardingCompany',
        ),
    ]
